version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "Hello from build"
  test:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "Hello from test"
workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
        filters:
          tags:
            ignore: 3.0
  tagged-build:
    jobs:
      - test:
        filters:
          tags:
            only: 3.0
