version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "hello from build"
  deploy:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "hello from deploy"
  test:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "hello from test"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:  # required since `test` has tag filters AND requires `build`
            tags:
              only: /^.*/
      # - test:
      #     requires:
      #       - build
      #     filters:  # required since `deploy` has tag filters AND requires `test`
      #       tags:
      #         only: /^v.*/
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
